"""initial

Revision ID: df88e8bbbbc7
Revises: 
Create Date: 2026-06-16 22:48:17.630982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df88e8bbbbc7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight_searches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('origin', sa.String(length=3), nullable=False),
    sa.Column('destination', sa.String(length=3), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('passengers', sa.Integer(), nullable=False),
    sa.Column('cabin_class', sa.String(length=20), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('raw_response', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flight_searches_cache_key'), 'flight_searches', ['cache_key'], unique=True)
    op.create_index('ix_flight_searches_route_dates', 'flight_searches', ['origin', 'destination', 'departure_date', 'return_date'], unique=False)
    op.create_table('offer_price_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_key', sa.String(length=7), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('min_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_price_history_route_date', 'offer_price_history', ['route_key', 'departure_date'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('flight_offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('search_id', sa.UUID(), nullable=False),
    sa.Column('provider_offer_id', sa.String(length=200), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('price_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_currency', sa.String(length=3), nullable=False),
    sa.Column('airlines', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('outbound_route', sa.Text(), nullable=False),
    sa.Column('return_route', sa.Text(), nullable=False),
    sa.Column('outbound_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('return_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stops_outbound', sa.Integer(), nullable=False),
    sa.Column('stops_return', sa.Integer(), nullable=False),
    sa.Column('is_nonstop', sa.Boolean(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['flight_searches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_flight_offers_price', 'flight_offers', ['price_amount'], unique=False)
    op.create_index('ix_flight_offers_search_id', 'flight_offers', ['search_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_flight_offers_search_id', table_name='flight_offers')
    op.drop_index('ix_flight_offers_price', table_name='flight_offers')
    op.drop_table('flight_offers')
    op.drop_table('providers')
    op.drop_index('ix_price_history_route_date', table_name='offer_price_history')
    op.drop_table('offer_price_history')
    op.drop_index('ix_flight_searches_route_dates', table_name='flight_searches')
    op.drop_index(op.f('ix_flight_searches_cache_key'), table_name='flight_searches')
    op.drop_table('flight_searches')
    # ### end Alembic commands ###
